### ISSUE TITLE
[@thumbtack/thumbprint-react]: Enable `HorizontalRule` to have prop-configurable vertical (and maybe horizontal) margin

### ISSUE THREAD

**Issue by webbower** [thumbtack/thumbprint#549] opened 2019-11-05 01:04 UTC
The default styling for `HorizontalRule` has a top/bottom margin of 8px (`$tp-space__2`) which isn't always enough. To spare the need to add a wrapper element to increase the vertical spacing, it would be great if that was prop-configurable.

And if it works for the design system, make the left/right margin prop-configurable.

I don't know whether this would look like enabling `className` or adding `hSpace` and `vSpace` props.

**Comment by danoc** [comment] 2020-01-07 19:53
Hey Matt! Thanks for the issue. I'm going to close this one as a duplicate of https://github.com/thumbtack/thumbprint/issues/549. The solution we come up with there will also apply to `HorizontalRule`.

**Closed by danoc** 2020-01-07 19:53 UTC
