### ISSUE TITLE
[@thumbtack/thumbprint-scss]: Make responsive mixins easier to use from memory

### ISSUE THREAD

**Issue by benknight** [thumbtack/thumbprint#153] opened 2019-03-05 03:47 UTC
In my opinion, it's difficult to use the `tp-respond-below` and `tp-respond-above` mixins purely from memory because with the $tp variables, it's actually quite verbose.  I generally resort to copying and pasting them from some other code, which is a minor annoyance.

On the helpcenter repo we've been using the following convenience methods, which I find a lot easier to remember:

```scss
@import 'node_modules/@thumbtack/thumbprint-scss/mixins';

$breakpoints: (
  small: $tp-breakpoint__small,
  medium: $tp-breakpoint__medium,
  large: $tp-breakpoint__large,
);

@mixin respond-above($width) {
  @include tp-respond-above(map-get($breakpoints, $width)) {
    @content;
  }
}

@mixin respond-below($width) {
  @include tp-respond-below(map-get($breakpoints, $width)) {
    @content;
  }
}
```
```scss
// Usage:

.component {
  @include respond-above(medium) {
    // ...
  }
}
```

**Comment by danoc** [comment] 2019-03-06 21:52
Hi Ben! Thanks for the suggestion. @tomgenoni would be best to provide feedback here.

**Comment by tomgenoni** [comment] 2019-03-06 22:03
Thanks @benknight. I started using the `tp-` prefix on everything when I first started working on Thumbprint to help distinguish it from legacy code. But I agree the verbosity of it sacrifices ease of use and is something I've wanted to refactor.

**Comment by benknight** [comment] 2019-03-07 04:19
@tomgenoni for me it's less about the `tp-` prefix, that's easy enough to understand.  It's about having to remember the variable as well.

On the other hand I'm not sure there's a solution here that avoids introducing a breaking change.

For example, if we refactored it so that usage looked liked `tp-respond-above(large)` this would require updating that mixins usage globally.  Not a huge effort, pretty much just a find/replace with a regex, but I would imagine breaking changes are to be avoided?

**Comment by tomgenoni** [comment] 2019-03-07 18:39
Yeah, we do global migrations caused by breaking changes somewhat regularly. At this point our `tp-*` classes are only used on legacy pages or as backups where the React component either doesn't exist or is insufficient, so converting this to something terser, like we did with the Atomic classes, makes sense.

**Comment by danoc** [comment] 2020-01-07 19:04
@tomgenoni — Thoughts on closing this? Less important IMO since Atomic has responsive classes.

**Comment by tomgenoni** [comment] 2020-01-07 19:38
Yeah, doesn't look like the usage of these is frequent enough to warrant a big change.

**Closed** 2020-01-07 20:53 UTC
