### ISSUE TITLE
Modal Curtain docs not listed in Components sidebar nav

### ISSUE THREAD

**Issue by tomgenoni** [thumbtack/thumbprint#149] opened 2019-02-26 18:44 UTC
The deprecation warning on https://thumbprint.design/components/modal-standard/react/ points to https://thumbprint.design/components/modal-curtain/react/ but that link isn't in the sidebar. Not sure if that's intentional.

**Comment by danoc** [comment] 2019-03-29 20:56
Closing this as a duplicate of #3.

**Closed by danoc** 2019-03-29 20:56 UTC
